In [12]:
import numpy as np
a="jaymin"
a

'jaymin'

In [45]:
a=np.array([(1,2,3),(4,5,6)])

print(a)


[[1 2 3]
 [4 5 6]]


In [47]:
a=np.random.rand(3,4)
a

array([[0.9076445 , 0.41770675, 0.41128054, 0.09226691],
       [0.90589391, 0.72999444, 0.4581301 , 0.93755042],
       [0.94675323, 0.29932127, 0.01095068, 0.22530943]])

In [52]:
pr=np.ones((3,4))
pr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
pra=np.eye(4)
pra

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
b1=a.reshape(4,-1)
b1

array([[0.9076445 , 0.41770675, 0.41128054],
       [0.09226691, 0.90589391, 0.72999444],
       [0.4581301 , 0.93755042, 0.94675323],
       [0.29932127, 0.01095068, 0.22530943]])

In [65]:
z=[1,2,3,4,5,6]
y=np.delete(z,3)
y

array([1, 2, 3, 5, 6])